-- SQL schema script for Jugaad Academic Resource Library

-- 1. Create the 'users' table
CREATE TABLE IF NOT EXISTS users (
    email TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT,
    year TEXT,
    campus TEXT,
    phone_number TEXT,
    trust_score INTEGER DEFAULT 50,
    attendance_cache JSONB DEFAULT '[]'::jsonb,
    marks_cache JSONB DEFAULT '[]'::jsonb,
    timetable_cache JSONB DEFAULT '[]'::jsonb,
    courses_cache JSONB DEFAULT '[]'::jsonb,
    last_sync TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the 'items' table
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT DEFAULT 'FOUND',
    title TEXT,
    description TEXT,
    category TEXT,
    location TEXT,
    user_email TEXT,
    photo_url TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create the 'notifications' table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    message TEXT,
    type TEXT DEFAULT 'broadcast',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security (RLS) to allow the anonymous client to read/write as configured in the app
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE items DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
