export const BRANCH_FILES = [
  { id: "ai", name: "Artificial Intelligence", file: "artificial-intelligence-curriculum-2021.pdf" },
  { id: "cse", name: "Computer Science & Engineering", file: "b-tech-in-computer-science-and-engineering.pdf" },
  { id: "biomed", name: "Biomedical Engineering", file: "biomedical-engineering-curriculum-2021.pdf" },
  { id: "biomed_mi", name: "Biomedical Engg. (Machine Intelligence)", file: "biomedical-engineering-machine-intelligence-curriculum-2021.pdf" },
  { id: "biotech_cb", name: "Biotech (Computational Biology)", file: "biotechnology-computational-biology-curriculum-2021.pdf" },
  { id: "biotech", name: "Biotechnology", file: "biotechnology-curriculum-2021.pdf" },
  { id: "biotech_ft", name: "Biotechnology (Food Technology)", file: "biotechnology-food-technology-curriculum-2021.pdf" },
  { id: "biotech_rm", name: "Biotech (Regenerative Medicine)", file: "biotechnology-with-specialization-in-regenerative-medicine-curriculum-2021.pdf" },
  { id: "chemical", name: "Chemical Engineering", file: "chemical-engineering-curriculum-2021.pdf" },
  { id: "civil", name: "Civil Engineering", file: "civil-engineering-curriculum-2021.pdf" },
  { id: "csbs", name: "Computer Science & Business Systems", file: "computer-science-and-business-system-curriculum-2021.pdf" },
  { id: "cse_ds", name: "CSE (Data Science)", file: "computer-science-and-engineering-data-science-curriculum-2021.pdf" },
  { id: "cse_ai", name: "CSE (Artificial Intelligence)", file: "computer-science-and-engineering-with-specialization-in-artificial-intelligence-curriculum-2021.pdf" },
  { id: "cse_bd", name: "CSE (Big Data Analytics)", file: "computer-science-and-engineering-with-specialization-in-big-data-analytics-curriculum-2021.pdf" },
  { id: "cse_cc", name: "CSE (Cloud Computing)", file: "computer-science-and-engineering-with-specialization-in-cloud-computing-curriculum-2021.pdf" },
  { id: "cse_cy", name: "CSE (Cybersecurity)", file: "computer-science-and-engineering-with-specialization-in-cybersecurity-curriculum-2021.pdf" },
  { id: "cse_it", name: "CSE (Information Technology)", file: "computer-science-and-engineering-with-specialization-in-information-technology-curriculum-2021.pdf" },
  { id: "cse_iot", name: "CSE (Internet of Things)", file: "computer-science-and-engineering-with-specialization-in-internet-of-things-curriculum-2021.pdf" },
  { id: "cse_se", name: "CSE (Software Engineering)", file: "computer-science-and-engineering-with-specialization-in-software-engineering-curriculum-2021.pdf" },
  { id: "eee", name: "Electrical & Electronics Engineering", file: "electrical-and-electronics-engineering-curriculum-2021.pdf" },
  { id: "ece_ds", name: "ECE (Data Science)", file: "electronics-and-communication-engg-with-spl-in-data-science-curriculum-2021.pdf" },
  { id: "ece", name: "Electronics & Communication Engineering", file: "electronics-and-communication-engineering-curriculum-2021.pdf" },
  { id: "ec_comp", name: "Electronics and Computer Engineering", file: "electronics-and-computer-engineering-curriculum-2021.pdf" },
  { id: "mechanical", name: "Mechanical Engineering", file: "mechanical-engineering-curriculum-2021.pdf" },
  { id: "mechatronics", name: "Mechatronics Engineering", file: "mechatronics-engineering-curriculum-2021.pdf" }
];
